<?xml version='1.0' encoding='utf-8'?>
	<!DOCTYPE TesterList [
		<!ELEMENT TesterList (Tester)*>
		<!ELEMENT Tester (ClassName, Description, TestsListRif)>
		<!ATTLIST Tester 
		    name     CDATA    #REQUIRED
		    skip     CDATA    #REQUIRED
		>
		<!ELEMENT ClassName (#PCDATA)>
		<!ELEMENT Description (#PCDATA)>
		<!ELEMENT TestsListRif (#PCDATA)>
	]>
<TesterList>
	
	<Tester name="UDPNodeMonitoringService test" skip="false">
		<ClassName>gr.aueb.jade.test.nodemonitoring.TesterAgent</ClassName>
		<Description> Testing the UDPNodeMonitoringService</Description>
		<TestsListRif>gr/aueb/jade/test/nodemonitoring/testList.xml</TestsListRif>
	</Tester>
	
</TesterList>
